### ISSUE TITLE
Add Pruner

### ISSUE THREAD

**Issue by admk** [Aaron-Zhao123/mayo-dev#12]
1. spawn masks in custom_getter as non-trainable tf variables.
2. assign values to masks after session init
3. start training

**Comment by admk** [comment]
Pruner added at a2db700.

**Comment by Aaron-Zhao123** [comment]
Pruner at a2db700 is not working for the following reason:

Mask setup requires calling get_variable in custom_getter, this results a nested call.

**Comment by Aaron-Zhao123** [comment]
Two strategies:

1. Spawn numpy masks and graph node mask*variable in custom getter. This requires reconstruction of the graph at different pruning iterations.

2. Spawn tf.variable masks and graph node mask*variable in custom getter. After session init or after loading the checkpoint, update the mask variables and then enter the training phase. This method has spawning masks be nested in the custom getter. I currently do not have an easy solution for this.

**Comment by Aaron-Zhao123** [comment]
I am thinking of using the first strategy, it is easier to implement, the only outcome is you cannot do multiple prunings in the same session.

**Comment by Aaron-Zhao123** [comment]
tried  ```self.get_variable = functools.partial(tf.get_variable)``` to maintain a separate copy of ```tf.get_variable```, but does not work.

I was thinking making a deep copy of ```tf.get_variable```, and call this copied function inside the ```with``` scope would overcome this issue....

**Comment by admk** [comment]
Added a revamped variable overrider.  Each child class of `BaseOverrider` must override both methods `_apply` and optionally `_update`, as shown below:
```python
class CustomOverrider(BaseOverrider):
    def _apply(self, getter, value):
        ...  # modify value, potentially use 
             # getter to instantiate a new variable
        return value

    def _update(self):
        ... # update variables instantiated in `_apply`
```

The method `_apply` is used when instantiating the network to override variables with new implementations specified in `_apply`. If `_apply` is stateful, i.e., you define some tf variables within `_apply`, then `_update` should be supplied as well to assign updated values to the tf variables defined in `_apply`.
